# Automatically generated by nvidia_driver_from_redist rule for NVIDIA driver %{driver-version}
# This BUILD file is for the external repository @nvidia_driver

load("@rules_cc//cc:cc_import.bzl", "cc_import")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

# Filegroup for the EGL vendor JSON manifest
# This will be used as a 'data' dependency for tests that need to set __EGL_VENDOR_LIBRARY_FILENAMES
filegroup(
    name = "10_nvidia_json",
    srcs = ["nvidia_driver/etc/10_nvidia.json"],
)

# X11 and its dependencies, required by EGL and OpenGL.
filegroup(
    name = "sysroot_x_runtime_libs_files",
    srcs = [
        "sysroot_x_runtime/usr/lib/x86_64-linux-gnu/libX11.so.6",
        "sysroot_x_runtime/usr/lib/x86_64-linux-gnu/libxcb.so.1",
        "sysroot_x_runtime/usr/lib/x86_64-linux-gnu/libXau.so.6",
        "sysroot_x_runtime/usr/lib/x86_64-linux-gnu/libXdmcp.so.6",
        "sysroot_x_runtime/usr/lib/x86_64-linux-gnu/libXext.so.6",
        "sysroot_x_runtime/usr/lib/x86_64-linux-gnu/libbsd.so.0",
    ],
)

filegroup(
    name = "nvidia_egl_libs_files",
    srcs = [
        "nvidia_driver/lib/libEGL.so.1",
        "nvidia_driver/lib/libEGL_nvidia.so.0",
        "nvidia_driver/lib/libnvidia-eglcore.so.%{driver-version}",
        "nvidia_driver/lib/libnvidia-glcore.so.%{driver-version}",
        "nvidia_driver/lib/libnvidia-allocator.so.%{driver-version}",
        "nvidia_driver/lib/libnvidia-tls.so.%{driver-version}",
        "nvidia_driver/lib/libnvidia-glsi.so.%{driver-version}",
    ],
)

filegroup(
    name = "nvidia_opengl_libs_files", # Provides the OpenGL stack (for an EGL-created context)
    srcs = [
        "nvidia_driver/lib/libGL.so.1",
        "nvidia_driver/lib/libGLdispatch.so.0",
        "nvidia_driver/lib/libEGL_nvidia.so.0",
        "nvidia_driver/lib/libnvidia-glcore.so.%{driver-version}",
        "nvidia_driver/lib/libGLX.so.0",
        "nvidia_driver/lib/libGLX_nvidia.so.0",
        "nvidia_driver/lib/libnvidia-tls.so.%{driver-version}",
        "nvidia_driver/lib/libnvidia-glsi.so.%{driver-version}",
    ],
)

cc_library(
    name = "nvidia_egl_libs",
    srcs = [
        ":sysroot_x_runtime_libs_files",
        ":nvidia_egl_libs_files",
    ],
)

cc_library(
    name = "nvidia_opengl_libs", # Provides the OpenGL stack (for an EGL-created context)
    srcs = [
        ":sysroot_x_runtime_libs_files",
        ":nvidia_opengl_libs_files",
    ],
)
