name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'libogre-1.9-dev libglew-dev libfreeimage-dev freeglut3-dev libxmu-dev libxi-dev libignition-cmake1-dev libignition-math5-dev libignition-common2-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
